/*system configurations 0: off 1:on*/
#define MOVDIR64B_EMULATION 0
#define ALLOW_TDX_SINGLE_STEPPING 1
#define TURN_ON_INSTRUMENTATION_LOG 1
#define TURN_ON_INSTRUCTION_TRACER 0
#define DETECT_SPECIFIC_KHOLE_MAPPING 1

#define ENABLE_TDH_SERVTD_BIND 0

#if TURN_ON_INSTRUCTION_TRACER == 1
#ifndef INSTRUCTION_TRACER_ON
    #define INSTRUCTION_TRACER_ON
#endif
#endif

#if TURN_ON_INSTRUMENTATION_LOG == 1
#ifndef INSTRUMENTATION_LOG_ON
    #define INSTRUMENTATION_LOG_ON
#endif
#endif

#if MOVDIR64B_EMULATION == 1
#ifndef EMULATE_MOVDIR64B
        #define EMULATE_MOVDIR64B
#endif
#endif

#if ALLOW_TDX_SINGLE_STEPPING == 1
#ifndef SINGLE_STEP_TDX_MOD
    #define SINGLE_STEP_TDX_MOD
#endif
#endif

#ifndef SE_START_SEAM_STATE
    #define SE_START_SEAM_STATE SEAM_STATE_TEMP
#endif

#if ENABLE_TDH_SERVTD_BIND == 1
#ifndef TEST_TDH_SERVTD_BIND
    #define TEST_TDH_SERVTD_BIND
#endif
#endif

#if DETECT_SPECIFIC_KHOLE_MAPPING == 1
#ifndef DETECT_SPECIFIC_KEYHOLE_MAPPING
    #define DETECT_SPECIFIC_KEYHOLE_MAPPING
#endif
#endif